apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Zng/naxfEfHVRqbOO7qsMTi34BqUsaqbax1FcRg5yy0RQQRVXTSZ4g==,iv:X034ddCegjLtRZLLVWMwG9jIJ1zh3sHfONpjXAwrocY=,tag:0m1dSv80AJ2oqj4OZWq/Tw==,type:str]
sops:
  age:
    - recipient: age1ajvhjep46ztnq5n4zyxjjt4xyjw8hdqu3zm43t6xlctv2wsn030sj65ltk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQlVidlJmMDJ5aHFBT1Az
        QVV4V1JuNkY0SkZteDYvSmpZWFNTZ04vS1ZJCjdjNGRQMkk3UE5DUHFhSHlCT0Ry
        V2lJUFB2V1NobFM3YjhWMThSNzdPS0kKLS0tIFhYbXpJQ1pKSlZPQ0tTdFZpdmhP
        dGNSMENmUTEwV0p6ZkhNazIyRVJsNGMKy35sTWJKYLFy0iPd4bm95UosQ+17ZKdy
        xEcOt0aAUSnb5ux+wPaSe876cllaQJOYC4+zvpGmcN70pYjPTpE8+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T16:38:27Z"
  mac: ENC[AES256_GCM,data:5cb+N6cgqohkrmZfjnHpqcFJGM7jQBpCXUkPfbsVauAUPVEiwHfOLUHkYjx7CpP8bOTi6minhWsdlUGd4UBDmyO2WID6MmBiJKdi7Di8uoYStxasuDmzipuPktVeGa9Kld8+JEFzwpCEpIOg9uZID+E+RF8tM3yy6KbHAzPKObc=,iv:D6NIY3hiaFo+ylY3grPh97vrGLq7SF6A3fWX1Of6CXU=,tag:kfDlPAbLASogGFrLoBFzXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
