apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:7EFR9jPs3zQB8CMTZbTKJOXfmA==,iv:P943hTNtNHKtD+LyxEo6BuFgh5vYXZAKMFtvXEKj7/o=,tag:F7RMkSy1KVNUwv/iwmwIig==,type:str]
sops:
  age:
    - recipient: age1ajvhjep46ztnq5n4zyxjjt4xyjw8hdqu3zm43t6xlctv2wsn030sj65ltk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ckpmSllILzJNMmh4UzZk
        d2NpWGw2RnI2dXFML2xRa09yVnNEM1R0S2pZCkFCak9MdlpKRm9udXJIdFBnSU53
        Q242VlFUbk51aDZ4Uy9JWlRaY2M2OXMKLS0tIEVNWTNpWWtQSG1FRENrNFNsNGx0
        YmhoSnJxclNSQ3N2b3pwNnREc2lMS1kKSHcDiJGOlVvXMjUKNqhcBj7d8yyEAR7+
        Mkqoi86BUBi+S6NmF6KOcZjoU855w7DWia3Iow9tTqWQsWu+fTU2gg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T16:38:27Z"
  mac: ENC[AES256_GCM,data:ljno9mg9lWO9xqsEA4WOctYOd43SqH2LJKWWkAaDqr8/7qSwhRsyLI3xz62KSpYub1IBURizQwSqpvvYjKSvQU7/nbw1Zr59uYtC6RccmU4Md2FkBBwGiqWZc32PWGaLKnQ65/qqky2ESWU15CemoghNyoOP9nY2Hwl6KUGiquk=,iv:Jsl3nCLWvPCo8OZIGozTeD0Mak1vNbkoeO61T8t4CnY=,tag:PgAU8/d770e88kd4eqJzqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
