apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:S45e30/Jy8dB2QXjPcZyamxMyql3FVOeL1cfW5OR9K0=,iv:Elz0Tj9HMD23J2V6rhb3e/c6Mu1ewU7pMwScwVIoNEQ=,tag:26TBSogjPx99RraL+/FJZA==,type:str]
sops:
  age:
    - recipient: age1ajvhjep46ztnq5n4zyxjjt4xyjw8hdqu3zm43t6xlctv2wsn030sj65ltk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMFVER0R1Y2d2ZS9hTWV1
        QTZlOTRpOFRMak8wS2VyTGx5c0hsR2hWSHpJCncwVUltUkxiWm90NzRMUWs1V1A1
        ZDZOZDFaaG5hMGEyYUl0WTdXWFBDM00KLS0tIDJNQzB5YVpobmdFVzkvYUJ4NzQ2
        b1FCZVI0V2c5MFhYSlZnVWprZ3lidjQKl/mnCK6LhCYtV1TLWGS0dNUBMhxWZBmx
        S+HBPf6za15yhUzRhl8jgDQkN0vl79NxA4EKLKQ5i4TRrTGcxqdKGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T16:38:27Z"
  mac: ENC[AES256_GCM,data:yjKFZdCYa3+DIyicqbiE6u/mfbm+hj/vhMkhEb8es58qa0FtYzwge736EA+/qL9T5ANwcjpSmisKU93raRm7BNg9bfSmt4vGLSEENe5Ta0dLOq5DdoUgjGc3BpgcFVrGpE4tNZGRpgyutMTOacr9lhTaXSDIatoLajKD9DjIInA=,iv:WdBhpSo0Bz6D+pkvLMWKXYBTM0dKOdb9nhB/8f8VsnE=,tag:NPLl3qHeLv8e75Jt3+LBmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
