apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:S9Q0dSQg6YwHfoc1cweLLHBvl0xMfONq2OMn0nUK+Y8elw6JJNAWvwUvmAkClXoIer8qSUErGpMJmoHt3vxpb/Q45OSu5cN0uVekUB5fLFCu9a16UX6HyPmXooHiSOOb2lyOMDsZQUEysrPy8hZz7A8msEmDVpF4iQH7goTgW7B0Z60P80qrXxRRPVzAQC9kiRc2aInagSfmtyDyNNP4GsvWAZNSKWpuw7osVQPuX+0zIP/a,iv:OyFhgetHb4oKRrYsLKSJbEbRl/G7s6JB4JM+2m0FIgY=,tag:BBkpTux0Mqv/Ka0i4Eqv6Q==,type:str]
sops:
  age:
    - recipient: age1ajvhjep46ztnq5n4zyxjjt4xyjw8hdqu3zm43t6xlctv2wsn030sj65ltk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSHkvc3QvVFYvQWd3bitM
        bFhTSkQzNk15SUtmOWs0TUhsRFpvZGd0aEJnCjhEUXNDTHY2aldPT09QT1RFRU1t
        SDlkcmtWNmV3U3hrak96QXJudkQ5ZzAKLS0tIGFsMjZDZ2hYMkZLR2ZIMC8xaGNS
        SVVMTG90QXB6dEtZb2srQ0xLQzhubjQKazrLW2pCmTZqJ35oXkw/7bMtAQMyzRGf
        h0WnuYmxp9l7VqYjlVDljKval+EBnkyxDMxRAELQpGEESZgpfYef6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T16:38:27Z"
  mac: ENC[AES256_GCM,data:+2wz59ZRxObmUaYGonyaC7VBZiBE1fLE+HdYeeMHUX8ZVrcaZmaeXYZazqkQM1OBawfVP17NiF+LB+jmZGHwD76lD+EfiUll/ZpHLYT3XsyvLYx4XwbBRbyux57Cc6RtX0Rd3vBXb22RrXBfW4dhVxQOisnoQmkQCYB6GhcQ0UI=,iv:cK+hTHc5txXSamTPJfGggRFNoMuHFSHWGsrqHQpHgGg=,tag:j0EA8zRitPJoFBvo5q4tBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
