apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:vx9CbNNvc5JHSl128pWTsBoda3Pww8wbySpkNtLHe8VyU4dOHSqIVA==,iv:0vPcRDz0vqhlGWebkZbtibYh5Os7sOXEhn1u+2xHvtE=,tag:Fx8/lF4IJXnwOfbVmglvmQ==,type:str]
sops:
  age:
    - recipient: age1ajvhjep46ztnq5n4zyxjjt4xyjw8hdqu3zm43t6xlctv2wsn030sj65ltk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3anFSUHBiSU82aHRBRTM4
        eFVnUlhPTFVmdDRzUjRka084ZlNXQzAwVFdVCkVmUGpMV2x0eDRLVmdTM05Mai9l
        OGRzQjRsUDJTeURSTDNEeDRjVXVQQjAKLS0tIGhJcGFpdjdCa2lubXk4dFNkK1R0
        M3UraGJKVDAwU0VJOEZ2K0dtZkUwTGsKpPiV1HGR4N9JVCWIxEpbI/e2K0VzZ3IZ
        WwQC0HC6Spo1KMUfpmNifSz3sTvRs5P24SIpXKqyB1jneQILbtU41Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T16:38:27Z"
  mac: ENC[AES256_GCM,data:z89CGePpHpkbh/Nfj365kaRfIO3JxWqgrYp+DY1K5Z0ovEqQZUyYtMB4YQHxV/oZLB1jFR+BVbOHlZThbtdAI3jDbmLYZz/6Nh0yV4u4Vy1ThHQHZMKsDvNcDOYG0mRfQ+zFXGqG2oFz5o3yQNcS2EoCSMlyQLbukZE2D/MibS4=,iv:/B2+6sYlO7IvgVoEgJougyymRQugCHsMQRKQ5NjikW8=,tag:XHuvG4Dpu/n1w1l4zycT1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
